tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#006d43",
                "inverse-primary": "#59de9b",
                "primary-fixed": "#78fbb6",
                "tertiary-fixed": "#9af6b8",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#3d4a41",
                "on-tertiary-container": "#00331a",
                "surface-bright": "#fdf8f5",
                "secondary": "#006e0c",
                "on-primary-container": "#00331d",
                "on-surface": "#1c1b1a",
                "inverse-surface": "#31302e",
                "surface-container-highest": "#e6e2df",
                "tertiary": "#006d3d",
                "surface-dim": "#ddd9d6",
                "surface-container": "#f1edea",
                "primary-container": "#00a86b",
                "on-secondary": "#ffffff",
                "surface-tint": "#006d43",
                "surface-container-low": "#f7f3f0",
                "on-secondary-fixed": "#002201",
                "tertiary-fixed-dim": "#7ed99e",
                "secondary-fixed": "#92fa83",
                "on-secondary-container": "#00730d",
                "surface": "#fdf8f5",
                "on-error-container": "#93000a",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#005232",
                "on-primary": "#ffffff",
                "tertiary-container": "#49a46d",
                "error": "#ba1a1a",
                "on-secondary-fixed-variant": "#005307",
                "on-tertiary-fixed-variant": "#00522d",
                "on-tertiary": "#ffffff",
                "on-background": "#1c1b1a",
                "surface-variant": "#e6e2df",
                "primary-fixed-dim": "#59de9b",
                "on-tertiary-fixed": "#00210f",
                "secondary-container": "#8ff780",
                "outline-variant": "#bccabe",
                "on-primary-fixed": "#002111",
                "secondary-fixed-dim": "#77dd6a",
                "surface-container-high": "#ece7e4",
                "background": "#fdf8f5",
                "on-error": "#ffffff",
                "inverse-on-surface": "#f4f0ed",
                "outline": "#6d7a70",
                "primary-dark": "#013220",
                "contact-secondary": "#2d3436",
                "contact-background": "#faf9f6"
            },
            fontFamily: {
                "headline": ["Noto Serif", "serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
}
